pages:
  stage: build
  image: debian:stable
  script:
    - apt-get update --yes
    - apt-get install --yes apt-utils curl dpkg-dev gpg jq wget
    - gpg --import $GPG_PRIVATE_KEY
    - mkdir --parents public/debian
    - cd public/debian
    - gpg --armor --export $GPG_KEY_ID > public_key.gpg
    - 'curl --header "PRIVATE-TOKEN: $PERSONAL_TOKEN" https://gitlab.com/api/v4/projects/pag-station%2Fquick-automation-devtool/releases?per_page=5 | jq -r ".[].assets.links | .[] | select((.link_type == \"package\") and (.name|endswith(\".deb\"))) | \"\(.direct_asset_url) \(.name)\"" | while read -r url name; do wget "$url" --output-document "$name"; done'
    - dpkg-scanpackages --multiversion . > Packages
    - gzip -k -f Packages
    - apt-ftparchive release . > Release
    - gpg --default-key "$GPG_KEY_ID" -abs -o - Release > Release.gpg
    - gpg --default-key "$GPG_KEY_ID" --clearsign -o - Release > InRelease
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"
